name: Reusable Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: echo "The input was ${{ inputs.example_input }}"
